### ISSUE TITLE
Doesn't calculate leap years correctly

### ISSUE THREAD

**Issue by 0atman** [gauravnumber/ifc-cli#1]
https://github.com/gauravnumber/ifc-cli/blob/main/src/index.ts#L48

That you've commented out this code makes me think you KNOW this :wink:

**Comment by gauravnumber** [comment]
I know. Currently `ifc-cli` only convert current date to IFC, so there is no need to complicate things, but in future release. I am going to let, user manually input any date to IFC. That time it is perfect to rearrange some code.

**Comment by 0atman** [comment]
Oh I see! This works because you're letting `Date` calculate the number of days into the year? That's quite elegeant. Thanks dude!
